apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment
  namespace: ums
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enrollment
  template:
    metadata:
      labels:
        app: enrollment
    spec:
      containers:
        - name: enrollment
          image: docker.io/dtummidibits/enrolment-service:5.0
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672/
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: enrollment-config
                  key: RABBITMQ_EXCHANGE
          envFrom:
            - secretRef:
                name: ums-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment
  namespace: ums
spec:
  type: NodePort
  selector:
    app: enrollment
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http