apiVersion: v1
kind: Secret
metadata:
  name: ums-secrets
  namespace: ums
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= 
  POSTGRES_PASSWORD: cG9zdGdyZXMtcGFzc3dvcmQ=
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q= 
  POSTGRES_DB: ZW5yb2xsbWVudF9kYg==